# Generated by Django 4.2.7 on 2024-02-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zshopapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblitemmaster',
            name='os',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, max_length=50, null=True),
        ),
    ]
