# Generated by Django 4.2.7 on 2024-02-26 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zshopapp', '0003_tbluserdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblusermaster',
            old_name='pcname',
            new_name='Area',
        ),
        migrations.AddField(
            model_name='tblusermaster',
            name='user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
