# Generated by Django 4.2.7 on 2024-02-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zshopapp', '0004_rename_pcname_tblusermaster_area_tblusermaster_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbldepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcode', models.IntegerField(blank=True, null=True)),
                ('dname', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicleno', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('pin', models.CharField(blank=True, max_length=50, null=True)),
                ('phoneno', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile', models.CharField(blank=True, max_length=50, null=True)),
                ('cperson', models.CharField(blank=True, max_length=50, null=True)),
                ('regno', models.CharField(blank=True, max_length=50, null=True)),
                ('lescenseno', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
