# Generated by Django 4.2.7 on 2024-02-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zshopapp', '0005_tbldepot'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbldepot',
            name='company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
