# Generated by Django 4.2.7 on 2024-02-26 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zshopapp', '0006_tbldepot_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblusermaster',
            old_name='Area',
            new_name='area',
        ),
    ]
