# Generated by Django 4.2.7 on 2024-02-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zshopapp', '0007_rename_area_tblusermaster_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbluserdetails',
            name='area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
