# Generated by Django 4.2.7 on 2024-02-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zshopapp', '0008_tbluserdetails_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblbusinessissue',
            name='area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tblgeneralledger',
            name='area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tbltransactionreceipt',
            name='area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
