# Generated by Django 4.2.7 on 2024-04-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zshopapp', '0010_tblaccgroup_area_tblaccountgroup_area_tblbatch_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblgeneralledger',
            name='vdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
