# Generated by Django 4.2.7 on 2024-04-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zshopapp', '0011_alter_tblgeneralledger_vdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblbusinessissue',
            name='issuedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
