# Generated by Django 4.2.7 on 2024-04-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zshopapp', '0012_alter_tblbusinessissue_issuedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblinventory',
            name='invdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
