# Generated by Django 4.2.7 on 2024-04-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zshopapp', '0013_alter_tblinventory_invdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbltransactionreceipt',
            name='recptdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
