# Generated by Django 4.2.7 on 2024-05-09 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zshopapp', '0015_alter_tblcompanymaster_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblcompanymaster',
            options={},
        ),
        migrations.AlterModelManagers(
            name='tblcompanymaster',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='tblcompanymaster',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='tblcompanymaster',
            name='email',
        ),
        migrations.RemoveField(
            model_name='tblcompanymaster',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='tblcompanymaster',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='tblcompanymaster',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='tblcompanymaster',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='tblcompanymaster',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='tblcompanymaster',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='tblcompanymaster',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='tblcompanymaster',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='tblcompanymaster',
            name='username',
        ),
    ]
