# Generated by Django 4.2.7 on 2024-05-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zshopapp', '0018_alter_tblcompanymaster_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblissuedetails',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tblreceiptdetails',
            name='id',
        ),
        migrations.AddField(
            model_name='tblbusinessissue',
            name='biid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tblissuedetails',
            name='issueid',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tblreceiptdetails',
            name='rdid',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbltransactionreceipt',
            name='trid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
