# Generated by Django 4.2.7 on 2024-05-25 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zshopapp', '0019_remove_tblissuedetails_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblbusinessissue',
            name='tblissuedetails',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zshopapp.tblissuedetails'),
            preserve_default=False,
        ),
    ]
