# Generated by Django 4.2.7 on 2024-05-25 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zshopapp', '0020_tblbusinessissue_tblissuedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbltransactionreceipt',
            name='recptdetails',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zshopapp.tblreceiptdetails'),
            preserve_default=False,
        ),
    ]
