# Generated by Django 4.2.7 on 2024-05-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zshopapp', '0021_tbltransactionreceipt_recptdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblbusinessissue',
            name='refno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
