# Generated by Django 4.2.7 on 2024-05-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zshopapp', '0022_tblbusinessissue_refno'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblbusinessissue',
            name='qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tbltransactionreceipt',
            name='qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, max_length=50, null=True),
        ),
    ]
