# Generated by Django 4.2.7 on 2024-09-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zshopapp', '0023_tblbusinessissue_qty_tbltransactionreceipt_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tblcomplaintdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vno', models.IntegerField(blank=True, null=True)),
                ('battery', models.IntegerField(blank=True, null=True)),
                ('facecover', models.IntegerField(blank=True, null=True)),
                ('backcover', models.IntegerField(blank=True, null=True)),
                ('mmc', models.IntegerField(blank=True, null=True)),
                ('sim', models.IntegerField(blank=True, null=True)),
                ('charger', models.IntegerField(blank=True, null=True)),
                ('nsignal', models.IntegerField(blank=True, null=True)),
                ('ncharge', models.IntegerField(blank=True, null=True)),
                ('npower', models.IntegerField(blank=True, null=True)),
                ('mnt', models.IntegerField(blank=True, null=True)),
                ('cnt', models.IntegerField(blank=True, null=True)),
                ('fnt', models.IntegerField(blank=True, null=True)),
                ('snt', models.IntegerField(blank=True, null=True)),
                ('keypadnt', models.IntegerField(blank=True, null=True)),
                ('lcdprob', models.IntegerField(blank=True, null=True)),
                ('password', models.IntegerField(blank=True, null=True)),
                ('imei', models.IntegerField(blank=True, null=True)),
                ('addate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
