# Generated by Django 4.2.7 on 2024-09-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zshopapp', '0024_tblcomplaintdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblcomplaintdetails',
            name='imei',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tblcomplaintdetails',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
