# Generated by Django 4.2.7 on 2024-10-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zshopapp', '0026_tblcomplaintdetails_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbljob',
            fields=[
                ('jidmain', models.IntegerField(primary_key=True, serialize=False)),
                ('jid', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('note', models.CharField(blank=True, max_length=150, null=True)),
                ('wcategoryid', models.IntegerField(blank=True, null=True)),
                ('iqamano', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=150, null=True)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('whatsappno', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tblworkcategory',
            fields=[
                ('widmain', models.IntegerField(primary_key=True, serialize=False)),
                ('wid', models.IntegerField(blank=True, null=True)),
                ('wcategory', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
