# Generated by Django 4.2.7 on 2024-10-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zshopapp', '0027_tbljob_tblworkcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbljob',
            name='company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tblworkcategory',
            name='company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
