# Generated by Django 4.2.7 on 2024-10-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zshopapp', '0028_tbljob_company_tblworkcategory_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbljob',
            name='iqamano',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
