# Generated by Django 4.2.7 on 2024-10-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zshopapp', '0029_alter_tbljob_iqamano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbljob',
            name='mobile',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='tbljob',
            name='whatsappno',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
