# Generated by Django 4.2.7 on 2024-10-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zshopapp', '0030_alter_tbljob_mobile_alter_tbljob_whatsappno'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblbatch',
            name='crate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
