# Generated by Django 4.2.7 on 2024-11-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zshopapp', '0031_tblbatch_crate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbltransactionreceipt',
            name='pbill',
            field=models.ImageField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
