# Generated by Django 4.2.7 on 2024-12-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zshopapp', '0032_tbltransactionreceipt_pbill'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblbusinessissue',
            name='discperc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tbltransactionreceipt',
            name='discperc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, max_length=50, null=True),
        ),
    ]
