# Generated by Django 4.2.7 on 2025-02-18 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zshopapp', '0034_alter_tbltransactionreceipt_pbill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tblproductsetdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('slno', models.CharField(blank=True, max_length=50, null=True)),
                ('item', models.IntegerField(blank=True, null=True)),
                ('qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, max_length=50, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, max_length=50, null=True)),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tblrepackingdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vno', models.IntegerField()),
                ('slno', models.CharField(blank=True, max_length=50, null=True)),
                ('itemid', models.IntegerField(blank=True, null=True)),
                ('batchcode', models.CharField(blank=True, max_length=150, null=True)),
                ('qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, max_length=50, null=True)),
                ('prate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, max_length=50, null=True)),
                ('crate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, max_length=50, null=True)),
                ('srate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, max_length=50, null=True)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, max_length=50, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, max_length=50, null=True)),
                ('depoid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, max_length=50, null=True)),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tblrepacking',
            fields=[
                ('vno', models.IntegerField(primary_key=True, serialize=False)),
                ('vdate', models.DateTimeField(blank=True, null=True)),
                ('packdate', models.DateTimeField(blank=True, null=True)),
                ('narration', models.CharField(blank=True, max_length=50, null=True)),
                ('slno', models.CharField(blank=True, max_length=50, null=True)),
                ('itemid', models.IntegerField(blank=True, null=True)),
                ('batchcode', models.CharField(blank=True, max_length=150, null=True)),
                ('qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, max_length=50, null=True)),
                ('prate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, max_length=50, null=True)),
                ('crate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, max_length=50, null=True)),
                ('srate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, max_length=50, null=True)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, max_length=50, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, max_length=50, null=True)),
                ('depoid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, max_length=50, null=True)),
                ('labourcharge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, max_length=50, null=True)),
                ('costfactor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, max_length=50, null=True)),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('tblrepackdetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zshopapp.tblrepackingdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Tblproductset',
            fields=[
                ('pid', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('item', models.IntegerField(blank=True, null=True)),
                ('qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, max_length=50, null=True)),
                ('mrate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, max_length=50, null=True)),
                ('lcharge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, max_length=50, null=True)),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('tblproddetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zshopapp.tblproductsetdetails')),
            ],
        ),
    ]
