# Generated by Django 4.2.7 on 2025-02-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zshopapp', '0035_tblproductsetdetails_tblrepackingdetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblproductset',
            name='itemname',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tblproductsetdetails',
            name='itemname',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
