# Generated by Django 4.2.7 on 2025-02-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zshopapp', '0036_tblproductset_itemname_tblproductsetdetails_itemname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblproductset',
            name='itemname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tblproductsetdetails',
            name='itemname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
