# Generated by Django 4.2.7 on 2025-02-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zshopapp', '0037_alter_tblproductset_itemname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblitemmaster',
            name='litid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
