# Generated by Django 4.2.7 on 2025-02-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zshopapp', '0038_tblitemmaster_litid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tblmnuseetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuid', models.IntegerField(blank=True, null=True)),
                ('presaleedit', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
