# Generated by Django 4.2.7 on 2025-02-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zshopapp', '0039_tblmnuseetings'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblmnuseetings',
            name='company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
