# Generated by Django 4.2.7 on 2025-03-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zshopapp', '0042_alter_tblmnuseetings_printheaderimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblmnuseetings',
            name='printheaderimage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
