# Generated by Django 4.2.7 on 2025-03-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zshopapp', '0043_alter_tblmnuseetings_printheaderimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblmnuseetings',
            name='printfooterimage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
